"use client";

import { NeynarContextProvider } from "@neynar/react";
import { ReactNode } from "react";
import { UserInitializer } from "./UserInitializer";

const NEYNAR_CLIENT_ID = process.env.NEXT_PUBLIC_NEYNAR_CLIENT_ID || "";

export function AuthProvider({ children }: { children: ReactNode }) {
  if (!NEYNAR_CLIENT_ID) {
    console.warn("NEXT_PUBLIC_NEYNAR_CLIENT_ID is not set");
  }

  return (
    <NeynarContextProvider
      settings={{
        clientId: NEYNAR_CLIENT_ID,
        eventsCallbacks: {
          onAuthSuccess: async (data) => {
            // This callback is triggered when user successfully authenticates
            // The UserInitializer component will handle the signer reconciliation flow
            // We could potentially access signed message/signature here if Neynar SDK exposes it
            console.log("[AuthProvider] ===== USER AUTHENTICATED =====");
            console.log("[AuthProvider] FID:", data.user?.fid);
            console.log("[AuthProvider] Signer UUID from Neynar:", data.user?.signer_uuid);
            console.log("[AuthProvider] ⚠️  NEW SIGNER GENERATED BY NEYNAR:", data.user?.signer_uuid);
            console.log("[AuthProvider] User data:", {
              username: data.user?.username,
              displayName: data.user?.display_name,
            });
            console.log("[AuthProvider] =====================================");
          },
          onSignout: () => {
            console.log("[AuthProvider] ===== USER SIGNED OUT =====");
          },
        },
      }}
    >
      <UserInitializer />
      {children}
    </NeynarContextProvider>
  );
}

